services:
  - type: web
    name: telegram-acesso-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_ID
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
